version: '3.8'

networks:
  fruitpicking-network:
    external: true

services:
  fruitpicking-mysql:
    image: mysql:8.0
    container_name: fruitpicking-mysql
    restart: always
    networks:
      - fruitpicking-network
    ports:
      - "33306:3306"
    volumes:
      - /data/fruitpicking-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fruitpicking

  fruitpicking-redis:
    image: redis:latest
    container_name: fruitpicking-redis
    restart: always
    networks:
      - fruitpicking-network
    ports:
      - "6390:6379"

  fruitpicking-app:
    image: openjdk:17
    container_name: fruitpicking-app
    restart: always
    networks:
      - fruitpicking-network
    ports:
      - "8083:8082"
    volumes:
      - ./app.jar:/app.jar
    command: java -jar /app.jar --server.address=0.0.0.0 --server.port=8082
    depends_on:
      - fruitpicking-mysql
      - fruitpicking-redis