server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://fruitpicking-mysql:3306/fruitpicking?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000

  # Redis 配置
  redis:
    host: fruitpicking-redis
    port: 6379
    password:
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  # Jackson 日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  mail:
    host: smtp.qq.com
    port: 465
    username: 1500183776@qq.com
    password: twekpecexfhxhiii
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            protocols: TLSv1.2
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.FruitPickingRobt.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    root: info
    com.FruitPickingRobt: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# 自定义应用配置
app:
  # 轨迹保留最大点数
  max-history-points: 200
  # 是否启用 Redis 缓存最新位置
  use-redis-cache: true

security:
  jwt:
    header: Authorization
    token-start-with: "Bearer"
    base64-secret: "your-256-bit-secret-key-here-please-use-a-long-random-string"   # 注意是 base64-secret
    token-validity-seconds: 86400   # 注意是 token-validity-seconds
    ignore-paths:
      - /api/v1/codes/**
      - /api/v1/users
      - /api/v1/users/login
      - /api/v1/password-reset
      - /error
      - /api/history
      - /api/latest
      - /ws/**
    admin-paths:
      - /api/v1/admin/**